-- ── REM-5: drop what REM-1 (expenses) and REM-2 (Hasad as a sales channel only) deprecated, and the demo-only
-- and reservation leftovers (docs/plans/REM-5.md, docs/decisions.md D-rem5-*). Before the first production
-- deployment, no production data exists.
--
-- 1. GUARD. History is never rewritten: if this database holds ANY row that uses a removed table or value, the
--    migration stops here and, because every pending migration runs in one transaction, NOTHING is changed.
--    Such databases (old demo or pre-REM-3 trial databases) are recreated, not upgraded.
-- 2. Drop the deprecation triggers on ledger_entries and their function; replace the narrowed CHECKs.
-- 3. Drop the deprecated tables (in dependency order, no CASCADE), the hasad_mock schema and columns
--    (generated by drizzle-kit from the complete schema, then reviewed by hand).
-- 4. Delete the leftover settings row of the removed Hasad integration.
-- 5. One supplier line per piece: UNIQUE(purchase_items.item_id) (the item views LEFT JOIN on it; the guard proved
--    no piece has two lines, and only createPurchase writes a line, once, for the piece it just created).
DO $$
DECLARE
  found text := '';
  n bigint;
  q record;
BEGIN
  FOR q IN
    SELECT * FROM (VALUES
      ('expenses (removed by REM-1)', 'SELECT count(*) FROM expenses'),
      ('hasad_withdrawals (removed by REM-2)', 'SELECT count(*) FROM hasad_withdrawals'),
      ('hasad_redemptions (removed by REM-2)', 'SELECT count(*) FROM hasad_redemptions'),
      ('hasad_redemption_items (removed by REM-2)', 'SELECT count(*) FROM hasad_redemption_items'),
      ('settlements: Hasad weight differences (removed by REM-2)', 'SELECT count(*) FROM settlements'),
      ('hasad_mock.customers', 'SELECT count(*) FROM hasad_mock.customers'),
      ('hasad_mock.withdrawals', 'SELECT count(*) FROM hasad_mock.withdrawals'),
      ('hasad_mock.api_calls', 'SELECT count(*) FROM hasad_mock.api_calls'),
      ('ledger_entries with event EXPENSE or HASAD_SETTLEMENT', $q$SELECT count(*) FROM ledger_entries WHERE event_type IN ('EXPENSE', 'HASAD_SETTLEMENT')$q$),
      ('inventory_movements of type HASAD_REDEMPTION', $q$SELECT count(*) FROM inventory_movements WHERE type = 'HASAD_REDEMPTION'$q$),
      ('item_status_history through RESERVED or REDEEMED', $q$SELECT count(*) FROM item_status_history WHERE from_status IN ('RESERVED', 'REDEEMED') OR to_status IN ('RESERVED', 'REDEEMED')$q$),
      ('jewelry_items RESERVED or REDEEMED, or with a reservation', $q$SELECT count(*) FROM jewelry_items WHERE status IN ('RESERVED', 'REDEEMED') OR reservation_ref IS NOT NULL OR reserved_at IS NOT NULL OR reserved_by IS NOT NULL$q$),
      ('jewelry_items whose old cost columns differ from acquisition_cost or the supplier line', $q$SELECT count(DISTINCT i.id) FROM jewelry_items i LEFT JOIN purchase_items pi ON pi.item_id = i.id
          WHERE i.total_cost <> i.acquisition_cost OR i.purchase_cost <> coalesce(pi.purchase_cost, i.acquisition_cost)
             OR i.making_cost <> coalesce(pi.making_cost, 0) OR i.other_cost <> coalesce(pi.other_cost, 0)$q$),
      ('audit_logs with a removed action', $q$SELECT count(*) FROM audit_logs WHERE action IN ('ITEM_RESERVED', 'ITEM_RELEASED', 'HASAD_WITHDRAWAL_RECEIVED', 'HASAD_WITHDRAWAL_OPENED', 'HASAD_WITHDRAWAL_COMPLETED', 'HASAD_WITHDRAWAL_CANCELLED', 'HASAD_REDEMPTION_ABORTED', 'HASAD_SETTLEMENT_CONFIRMED', 'EXPENSE_CREATED', 'EXPENSE_APPROVED', 'EXPENSE_REJECTED', 'DEMO_DATA_RESET')$q$),
      ('branches with a Hasad branch code', 'SELECT count(*) FROM branches WHERE hasad_branch_code IS NOT NULL'),
      ('sessions marked simulated (demo presence)', 'SELECT count(*) FROM sessions WHERE is_simulated'),
      ('pieces with more than one supplier line (purchase_items)', 'SELECT count(*) FROM (SELECT item_id FROM purchase_items GROUP BY item_id HAVING count(*) > 1) d')
    ) AS v(label, query)
  LOOP
    EXECUTE q.query INTO n;
    IF n > 0 THEN
      found := found || E'\n  ' || q.label || ': ' || n;
    END IF;
  END LOOP;
  IF found <> '' THEN
    RAISE EXCEPTION USING ERRCODE = 'restrict_violation',
      MESSAGE = 'Migration 0016 (REM-5) stopped: this database still holds data from removed features:' || found
        || E'\nNothing was changed. Databases with demo or pre-REM-3 history are not upgraded: create a new database'
        || E'\n(local: delete the PGLITE_DIR folder, default .data/pglite, and run `npm run demo`; server: a new database and `npm run bootstrap`).',
      HINT = 'docs/DEPLOYMENT.md, section "REM-5".';
  END IF;
END $$;--> statement-breakpoint
-- allow-destructive: REM-5 replaces this REM-1 trigger with the narrowed ck_ledger_entries_event_type (EXPENSE removed)
DROP TRIGGER "trg_ledger_entries_no_expense" ON "ledger_entries";--> statement-breakpoint
-- allow-destructive: REM-5 replaces this REM-2 trigger with the narrowed ck_ledger_entries_event_type (HASAD_SETTLEMENT removed)
DROP TRIGGER "trg_ledger_entries_no_hasad_settlement" ON "ledger_entries";--> statement-breakpoint
-- allow-destructive: REM-5 replaces the CHECK without EXPENSE and HASAD_SETTLEMENT (the guard proved no row uses them)
ALTER TABLE "ledger_entries" DROP CONSTRAINT "ck_ledger_entries_event_type";--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ck_ledger_entries_event_type" CHECK (event_type IN ('SALE', 'SALE_VOID', 'REVERSAL', 'SCRAP_PURCHASE', 'SUPPLIER_MAKING_CHARGE', 'HASAD_RECEIVABLE_SETTLEMENT'));--> statement-breakpoint
-- allow-destructive: REM-5 replaces the CHECK without HASAD_REDEMPTION (the guard proved no row uses it)
ALTER TABLE "inventory_movements" DROP CONSTRAINT "ck_inventory_movements_type";--> statement-breakpoint
ALTER TABLE "inventory_movements" ADD CONSTRAINT "ck_inventory_movements_type" CHECK (type IN ('PURCHASE', 'SALE', 'TRANSFER_IN', 'TRANSFER_OUT', 'RETURN', 'ADJUSTMENT', 'DAMAGE'));--> statement-breakpoint
-- allow-destructive: REM-5 replaces the CHECK without RESERVED and REDEEMED (the guard proved no row uses them)
ALTER TABLE "jewelry_items" DROP CONSTRAINT "ck_jewelry_items_status";--> statement-breakpoint
ALTER TABLE "jewelry_items" ADD CONSTRAINT "ck_jewelry_items_status" CHECK (status IN ('AVAILABLE', 'SOLD', 'TRANSFERRED', 'DAMAGED', 'RETURNED'));--> statement-breakpoint
-- allow-destructive: REM-5 replaces the CHECK without RESERVED and REDEEMED (the guard proved no row uses them)
ALTER TABLE "item_status_history" DROP CONSTRAINT "ck_item_status_history_from_status";--> statement-breakpoint
ALTER TABLE "item_status_history" ADD CONSTRAINT "ck_item_status_history_from_status" CHECK (from_status IS NULL OR from_status IN ('AVAILABLE', 'SOLD', 'TRANSFERRED', 'DAMAGED', 'RETURNED', 'PURCHASED', 'RECEIVED'));--> statement-breakpoint
-- allow-destructive: REM-5 replaces the CHECK without RESERVED and REDEEMED (the guard proved no row uses them)
ALTER TABLE "item_status_history" DROP CONSTRAINT "ck_item_status_history_to_status";--> statement-breakpoint
ALTER TABLE "item_status_history" ADD CONSTRAINT "ck_item_status_history_to_status" CHECK (to_status IN ('AVAILABLE', 'SOLD', 'TRANSFERRED', 'DAMAGED', 'RETURNED', 'PURCHASED', 'RECEIVED'));--> statement-breakpoint
-- allow-destructive: REM-5 drops the CHECKs of the deprecated item cost columns dropped below
ALTER TABLE "jewelry_items" DROP CONSTRAINT "ck_jewelry_items_total_cost_sum", DROP CONSTRAINT "ck_jewelry_items_purchase_cost_nonneg", DROP CONSTRAINT "ck_jewelry_items_making_cost_nonneg", DROP CONSTRAINT "ck_jewelry_items_other_cost_nonneg", DROP CONSTRAINT "ck_jewelry_items_total_cost_nonneg";--> statement-breakpoint
-- allow-destructive: REM-1 expenses table, no rows (guard); its CHECKs, index and trigger go with it
DROP TABLE "expenses";--> statement-breakpoint
-- allow-destructive: REM-2 Hasad weight-difference settlements, no rows (guard); refers to hasad_redemptions
DROP TABLE "settlements";--> statement-breakpoint
-- allow-destructive: REM-2 Hasad counter-session lines, no rows (guard); refers to hasad_redemptions
DROP TABLE "hasad_redemption_items";--> statement-breakpoint
-- allow-destructive: REM-2 Hasad counter sessions, no rows (guard); refers to hasad_withdrawals
DROP TABLE "hasad_redemptions";--> statement-breakpoint
-- allow-destructive: REM-2 Hasad withdrawal requests, no rows (guard)
DROP TABLE "hasad_withdrawals";--> statement-breakpoint
-- allow-destructive: REM-2 mock Hasad integration, no rows (guard)
DROP TABLE "hasad_mock"."api_calls";--> statement-breakpoint
-- allow-destructive: REM-2 mock Hasad integration, no rows (guard); refers to hasad_mock.customers
DROP TABLE "hasad_mock"."withdrawals";--> statement-breakpoint
-- allow-destructive: REM-2 mock Hasad integration, no rows (guard)
DROP TABLE "hasad_mock"."customers";--> statement-breakpoint
-- allow-destructive: REM-2 mock Hasad integration; the schema is empty now (no CASCADE)
DROP SCHEMA "hasad_mock";--> statement-breakpoint
-- allow-destructive: REM-5 drops the UNIQUE of the removed Hasad branch code (no value set: guard)
ALTER TABLE "branches" DROP CONSTRAINT "branches_hasad_branch_code_unique";--> statement-breakpoint
-- allow-destructive: REM-2 Hasad branch identifier, never set (guard)
ALTER TABLE "branches" DROP COLUMN "hasad_branch_code";--> statement-breakpoint
-- allow-destructive: Phase 2b deprecated cost column; equals the supplier line or the acquisition cost (guard)
ALTER TABLE "jewelry_items" DROP COLUMN "purchase_cost";--> statement-breakpoint
-- allow-destructive: Phase 2b deprecated cost column; equals the supplier line or 0 (guard)
ALTER TABLE "jewelry_items" DROP COLUMN "making_cost";--> statement-breakpoint
-- allow-destructive: Phase 2b deprecated cost column; equals the supplier line or 0 (guard)
ALTER TABLE "jewelry_items" DROP COLUMN "other_cost";--> statement-breakpoint
-- allow-destructive: Phase 2b deprecated cost column; equals acquisition_cost (guard)
ALTER TABLE "jewelry_items" DROP COLUMN "total_cost";--> statement-breakpoint
-- allow-destructive: RESERVED is removed; never set (guard)
ALTER TABLE "jewelry_items" DROP COLUMN "reservation_ref";--> statement-breakpoint
-- allow-destructive: RESERVED is removed; never set (guard)
ALTER TABLE "jewelry_items" DROP COLUMN "reserved_at";--> statement-breakpoint
-- allow-destructive: RESERVED is removed; never set (guard)
ALTER TABLE "jewelry_items" DROP COLUMN "reserved_by";--> statement-breakpoint
-- allow-destructive: demo presence flag removed by REM-3; never set (guard)
ALTER TABLE "sessions" DROP COLUMN "is_simulated";--> statement-breakpoint
-- allow-destructive: REM-5 drops the REM-1/REM-2 deprecation function; its last triggers are gone (tables dropped above)
DROP FUNCTION "jerp_refuse_deprecated_insert"();--> statement-breakpoint
-- allow-destructive: leftover setting of the removed Hasad integration (inserted by 0003, present in every database)
DELETE FROM "settings" WHERE "key" = 'hasad.enabledPerBranch';--> statement-breakpoint
ALTER TABLE "purchase_items" ADD CONSTRAINT "purchase_items_item_id_unique" UNIQUE("item_id");
